export const CONFIG = {
    // API_ROOT: 'http://10.0.2.2:55123/api',
    API_ROOT: 'http://13.67.77.215:8888/api',
    API_VERSION: '1.0',
    API_URL: {
        LOGIN: 'account/login',
        REGISTER: 'account/register',
        REQUEST_2FA: 'account/request2fa',
        VERIFY_2FA: 'account/verify2fa',
        SPECIALTIES: 'specialties',
        DOCTORS: 'doctors',
        DOCTOR: (id) => `doctors/${id}`,
        DOCTOR_WORKING_TIME: (doctorId) => `doctors/${doctorId}/workingTime`,
        DOCTOR_CHECKING_SERVICES: (doctorId) => `doctors/${doctorId}/checkingServices`,
        DOCTOR_REVIEWS: (doctorId) => `doctors/${doctorId}/reviews`,
        APPOINTMENTS: 'appointments',
        UPCOMING_APPOINTMENT: 'appointments/upcoming',
        APPOINTMENT: (id) => `appointments/${id}`,
        CANCEL_APPOINTMENT: (id) => `appointments/${id}/cancel`,
        DEVICES: 'devices',
        DEVICE_STATUS: (deviceUuid) => `devices/${deviceUuid}/status`,
        NOTIFICATIONS: 'notifications',
        NOTIFICATION_READ: (id) => `notifications/${id}/read`,
        NOTIFICATION_UNSEEN_COUNT: 'notifications/unseen/count',
        NOTIFICATION_UNSEEN_READ: 'notifications/unseen/read',
        USER_LOCATION: 'users/location',
        FAVORITE: 'favorites',
        REVIEWS: 'reviews'
    }
}